# Generated by Django 3.1.5 on 2021-02-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
    ]
