# Generated by Django 3.1.5 on 2021-02-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0002_auto_20210205_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_category_name', models.CharField(max_length=100, unique=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['food_category_name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.ImageField(height_field='height_field', null=True, upload_to='img/food_item', verbose_name='item_photo', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('isActive', models.BooleanField(default=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foods.foodcategory')),
            ],
            options={
                'ordering': ['category', 'food_name', 'slug'],
            },
        ),
    ]
